evaluate_api_task:
  description: >
    Thoroughly analyze the provided OpenAPI 3.0 contract and verify that the given API contract fully adheres to strict guidelines for building a Spring Boot application.
    The task involves verifying the following criteria as per the provided OpenAPI 3.0 contract:
    - Complete coverage of all data models, ensuring proper validation annotations, field types, and relationships.
    - Comprehensive endpoint specifications, adhering to RESTful conventions and proper use of HTTP methods.
    - Accurate and detailed request and response structures, including mandatory fields, data types, and appropriate status codes.
    - Service method mapping with correct exception handling, proper business logic separation, and adherence to Spring Boot service layer best practices.
    - Fully documented API with Swagger/OpenAPI specifications, including clear descriptions, versioning, and comprehensive metadata.
    - Security measures including authentication, secure communication (HTTPS), input validation, and secure headers for protection against threats.
  
    The final response must include:
    - Valid: True/False (Indicating whether the contract meets the guidelines)
    - Feedback: Detailed commentary on any missing or incomplete aspects, if applicable.
    - API contract to verify: {api_result}
    
  expected_output: >  
    - Pass: True/False (Indicating whether the contract is valid according to the guidelines)
    - Feedback: In-depth feedback with specific issues or areas for improvement if the contract fails to meet any criteria.
  agent: evaluate_api
