PromptInterpreterAgentTask:
  description: >
    Analyze the natural language UI prompt from {text} and extract structured UI/UX 
    requirements in a machine-readable JSON format.
  expected_output: >
    A JSON-based structured UI specification containing multiple pages, layouts, 
    components, styling preferences, and responsiveness details. The JSON should be 
    formatted to include primary color schemes, layout details, and interactive elements.
  agent: PromptInterpreterAgent
  steps:
    - Extract general design details (theme, color scheme, typography, dark mode, etc.).
    - Identify and structure page definitions (Login, Dashboard, Settings, etc.).
    - Parse UI components within each page (buttons, forms, tables, charts, etc.).
    - Define layout structure and responsiveness details (grid, flex, mobile stacking).
    - Format the extracted data into a well-structured JSON output.
  output_example: |
    {
      "app_name": "SaaS Dashboard",
      "theme": {
        "primary_color": "#007bff",
        "secondary_color": "#6c757d",
        "background": "#f8f9fa",
        "dark_mode": true
      },
      "pages": [
        {
          "name": "Login",
          "layout": {
            "background": "gradient or image overlay",
            "card": {
              "effect": "glassmorphic",
              "shadow": "soft",
              "border_radius": "12px"
            }
          },
          "components": [
            {
              "type": "logo",
              "position": "top-center"
            },
            {
              "type": "form",
              "fields": [
                {
                  "name": "email",
                  "label": "Email",
                  "icon": "email"
                },
                {
                  "name": "password",
                  "label": "Password",
                  "icon": "lock",
                  "visibility_toggle": true
                }
              ],
              "validation": {
                "error_color": "red",
                "success_color": "green"
              },
              "checkbox": {
                "label": "Remember Me"
              },
              "links": [
                {
                  "text": "Forgot Password?",
                  "action": "navigate"
                },
                {
                  "text": "Sign Up",
                  "action": "navigate"
                }
              ],
              "button": {
                "text": "Login",
                "style": {
                  "background": "gradient",
                  "hover_effect": "elevation"
                }
              }
            }
          ],
          "responsive": {
            "mobile": "stacked layout"
          }
        }
      ]
    }
